version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: ${SA_PASSWORD}
    networks:
      - ranch_db
    ports:
      - "1433:1433"

networks:
  ranch_db:
    driver: bridge
