name: Deploy SQL Server on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Ranch
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        envs: SA_PASSWORD
        script: |
          echo "Deploying SQL Server on Docker..."
          export SA_PASSWORD=${{ secrets.SA_PASSWORD }}
          docker-compose -f /path/to/your/docker-compose.yml up -d

