name: Deploy SQL Server on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Ranch
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH connection
      uses: appleboy/ssh-action@v1.0.3
      with:
       host: ${{ secrets.SSH_HOST }}
       username: ${{ secrets.SSH_USERNAME }}
       password: ${{ secrets.SSH_PASSWORD }}
       port: ${{ secrets.SSH_PORT }}
       script: |
                # Vérification et création du dossier /ranch_db
                if [ ! -d "/ranch_db" ]; then
                    echo "Le dossier /ranch_db n'existe pas. Création en cours..."
                    mkdir -p /ranch_db
                else
                    echo "Le dossier /ranch_db existe déjà."
                fi

                # Transfert de docker-compose.yml
                echo "Transfert de docker-compose.yml..."
                cat docker-compose.yml | ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cat > /ranch_db/docker-compose.yml"

                # Déploiement de SQL Server sur Docker
                echo "Déploiement de SQL Server sur Docker..."
                export SA_PASSWORD=${{ secrets.SA_PASSWORD }}
                docker-compose -f /ranch_db/docker-compose.yml up -d
